### ISSUE TITLE
You must use set() to the the mousedown property

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#1047]
Playing locally with tabs I get this error sometimes:

```
"Error: Assertion Failed: You must use set() to set the `mousedown` property (of <dummy@component:paper-tab::ember463>) to `true`.
    at new EmberError (http://localhost:4200/assets/vendor.js:13637:31)
    at assert (http://localhost:4200/assets/vendor.js:12501:23)
    at Class.SETTER_FUNCTION [as mousedown] (http://localhost:4200/assets/vendor.js:39547:56)
    at Class.handleMousedown (http://localhost:4200/assets/vendor.js:104713:22)
    at Backburner._run (http://localhost:4200/assets/vendor.js:28155:35)
    at Backburner._join (http://localhost:4200/assets/vendor.js:28133:29)
    at Backburner.join (http://localhost:4200/assets/vendor.js:27916:25)
    at join (http://localhost:4200/assets/vendor.js:16514:28)
    at HTMLElement.<anonymous> (http://localhost:4200/assets/vendor.js:16615:19)"
```

This is triggered by the RippleMixin which sets and read the `mousedown` property without using `.set()`.

Not sure why this is not ALWAYS triggered.

**Comment by DavidPhilip** [comment]
Also seeing this everytime I execute `click()` on a `paper-button` inside the tests.

**Comment by DavidPhilip** [comment]
Setting `noink=true` - removing the ripple effect - is a temporary workaround.
