### ISSUE TITLE
broccoli-sass conflicts with node-sass

### ISSUE THREAD

**Issue by altrim** [miguelcobain/ember-paper#12]
I just updated to 0.0.5 and when trying to run `ember serve` I get the following:

```
Object.keys called on non-object
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at StylePlugin.toTree (/Users/username/webapp/node_modules/ember-cli/lib/preprocessors/style-plugin.js:24:22)
    at /Users/username/webapp/node_modules/ember-cli/lib/preprocessors.js:104:26
    at Array.forEach (native)
    at processPlugins (/Users/username/webapp/node_modules/ember-cli/lib/preprocessors.js:103:11)
    at module.exports.preprocessCss (/Users/username/webapp/node_modules/ember-cli/lib/preprocessors.js:75:10)
    at Class.Addon.compileStyles (/Users/username/webapp/node_modules/ember-cli/lib/models/addon.js:193:27)
    at Class.Addon.treeForAddon (/Users/username/webapp/node_modules/ember-cli/lib/models/addon.js:174:25)
    at Class._treeFor (/Users/username/webapp/node_modules/ember-cli/lib/models/addon.js:118:31)
    at Class.treeFor (/Users/username/webapp/node_modules/ember-cli/lib/models/addon.js:97:19)
```
Then I noticed you use node-sass to compile the style sheets so just to tried to uninstall `broccoli-sass` and `ember serve` works fine and I get the compiled style sheets but now since I don't have `broccoli-sass` my styles aren't getting compiled. 

Is there a way to overcome this issue? I can see that `broccoli-sass` has `node-sass` as a dependency so I am not sure why this happens.

**Comment by mansona** [comment]
We have implemented sass for one of our ember-cli-addons by just using addon.sass https://github.com/Blooie/ember-cli-modal/blob/develop/addon/styles/addon.scss

The setup is a little bit complicated but it actually works. I hit an issue trying to develop my PR: https://github.com/miguelcobain/ember-paper/pull/22 in that the dummy app didn't update the css using npm start and I noticed that this is because of the post-install script. I could try and convert this to the proper way of doing addon sass if you like and submit a PR but the only downside is the the css ends up in vendor.css. If you are ok with that then I think it would be worth trying.

**Comment by miguelcobain** [comment]
@mansona if I remember correctly, that wasn't possible some time ago.

The styles ending up in vendor.css isn't a problem because thats what happens at the moment.
The current sass compilation was just a temporary workaround. A PR for that would be great!

**Comment by miguelcobain** [comment]
https://github.com/ember-cli/ember-cli/issues/2905

Let's wait on this issue to find out what is the recommended way to include sass in an addon.

**Comment by miguelcobain** [comment]
It's fixed! We still need to find a way to include sass, though.
