### ISSUE TITLE
Does not install with Ember 4.1.0

### ISSUE THREAD

**Issue by mattsimpson01** [miguelcobain/ember-paper#1202]
**Issue: Ember server crashes after installing ember paper.** 
Error message - this.registerPlugin is not a function

ember-cli: 4.1.0
node: 16.3.0
os: linux x64

**Steps to reproduce**
```
npm install -g ember-cli
ember new etest --lang en
ember install ember-paper
ember server
```
Log file 
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: this.registerPlugin is not a function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: this.registerPlugin is not a function
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: this.registerPlugin is not a function
    at TemplateCompiler.registerPlugins (/home/matt/dev/_current/ember/etest/node_modules/ember-composability-tools/node_modules/ember-cli-htmlbars/index.js:63:16)
    at new TemplateCompiler (/home/matt/dev/_current/ember/etest/node_modules/ember-composability-tools/node_modules/ember-cli-htmlbars/index.js:42:10)
    at Object.toTree (/home/matt/dev/_current/ember/etest/node_modules/ember-composability-tools/node_modules/ember-cli-htmlbars/ember-addon-main.js:47:16)
    at /home/matt/dev/_current/ember/etest/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>)
    at processPlugins (/home/matt/dev/_current/ember/etest/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at module.exports.preprocessTemplates (/home/matt/dev/_current/ember/etest/node_modules/ember-cli-preprocess-registry/preprocessors.js:169:10)
    at Class.compileTemplates (/home/matt/dev/_current/ember/etest/node_modules/ember-cli/lib/models/addon.js:1138:35)
    at Class.compileAddon (/home/matt/dev/_current/ember/etest/node_modules/ember-cli/lib/models/addon.js:1200:42)
    at Class.treeForAddon (/home/matt/dev/_current/ember/etest/node_modules/ember-cli/lib/models/addon.js:856:26)

**Comment by umitozturk** [comment]
after ember v3.27.0 (May 3, 2021), `registerPlugin / unregisterPlugin` was deprecated. that's the reason why you're getting this error.

you can see in here: https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md

**Comment by locks** [comment]
https://github.com/emberjs/ember.js/pull/19429#issuecomment-786403885 you can try pinning `ember-cli-htmlbars` to the suggested version.

**Comment by jacobq** [comment]
FWIW, I was able to get it to build with the following selective dependency resolution:

```json
  "resolutions": {
    "ember-paper/ember-composability-tools": "^1.1.0"
  },
```
Without `ember-composability-tools` update I got "this.registerPlugin is not a function"
(at one point I also had  `"ember-paper/ember-css-transitions": "^3.1.0"` for some reason but didn't need for simple case).

But then [`Ember.libraries.register('Ember Paper', '1.0.0-beta.36')`](https://github.com/miguelcobain/ember-paper/blob/b8401c6d2beb533f19a25cb5fc5470d066926ec5/index.js#L467) caused a runtime error even though it built OK (Tested with `ember-source: ~4.7.0`).

> Uncaught Error: Could not find module `ember-resolver` imported from `etest/app`

Annoyingly, [the docs](https://guides.emberjs.com/release/ember-inspector/info/#toc_registering-a-library) still say that `Ember.libraries.register(libraryName, libraryVersion);` is OK, but some GitHub searching [shows](https://github.com/emberjs/ember.js/issues/19705) [otherwise](https://github.com/emberjs/ember-inspector/blob/33b61245f6bef7adca44c262957bb171580fab9e/skeletons/web-extension/scripts/in-page-script.js#L30-L36).

Modifying `ember-paper`'s `index.js` as follows (hacky as it is) corrected that error:

```
 treeForVendor(tree) {
    let trees = [];
    
    let versionTree = writeFile(
      'ember-paper/register-version.js',
      //`Ember.libraries.register('Ember Paper', '${version}');`
      `let Ember;
try {
  Ember = requireModule('ember')['default'];
} catch {
  Ember = window.Ember;
}
Ember?.libraries?.register('Ember Paper', '${version}');`
    );
```

**Comment by mansona** [comment]
Hey folks this should all be fixed now 👍 ember-paper now tests from 3.28 - 6.x 👍
