### ISSUE TITLE
NPM error with installing node-sass

### ISSUE THREAD

**Issue by akhar** [miguelcobain/ember-paper#13]
Ember-CLI 0.1.4, fresh install.
 I tried ''npm install --save-dev ember-paper" and got this:

```
installing node-sass
\
> node-sass@1.2.3 install /home/akha/mbr/node_modules/ember-paper/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/akha/mbr/node_modules/ember-paper/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /home/akha/mbr/node_modules/ember-paper/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/akha/mbr/node_modules/ember-paper/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.16.0-28-generic
npm ERR! argv "/home/akha/.nvm/v0.11.14/bin/node" "/home/akha/.nvm/v0.11.14/bin/npm" "install" "node-sass"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
compiling CSS to /vendor with node-sass
./postinstall.sh: 13: ./postinstall.sh: ./node_modules/.bin/node-sass: not found

npm ERR! Linux 3.16.0-28-generic
npm ERR! argv "/home/akha/.nvm/v0.11.14/bin/node" "/home/akha/.nvm/v0.11.14/bin/npm" "install" "--save-dev" "ember-paper"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! ember-paper@0.0.7 postinstall: `./postinstall.sh`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ember-paper@0.0.7 postinstall script.
npm ERR! This is most likely a problem with the ember-paper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./postinstall.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-paper
npm ERR! There is likely additional logging output above.
```

**Comment by Rheaxu** [comment]
Got the same problem, and switching to 0.10.33 resolved it.
