### ISSUE TITLE
Installation & build problems

### ISSUE THREAD

**Issue by kazimuth** [miguelcobain/ember-paper#50]
In a fresh ember-cli project, the addon currently fails to install:
```sh
$ ember install:addon ember-paper
version: 0.2.0-beta.1
Installed packages for tooling via npm.
Cannot find module 'broccoli-autoprefixer'
Error: Cannot find module 'broccoli-autoprefixer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (fresh_project/node_modules/ember-paper/index.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
After adding `broccoli-autoprefixer`, it installs correctly.
However, then the build fails:
```sh
$ ember build
version: 0.2.0-beta.1
Build failed.
Cannot find module 'fresh_project/node_modules/broccoli-sass'
Error: Cannot find module 'fresh_project/node_modules/broccoli-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireLocal (fresh_project/node_modules/ember-cli/lib/utilities/require-local.js:6:10)
    at fresh_project/node_modules/ember-cli/lib/preprocessors/style-plugin.js:44:18
    at Array.map (native)
    at fresh_project/node_modules/ember-cli/lib/preprocessors/style-plugin.js:27:40
    at $$$internal$$tryCatch (fresh_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (fresh_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
```
After installing broccoli-sass, it fails in a different and interesting way:
```sh
$ ember build
version: 0.2.0-beta.1
Build failed.
fresh_project/tmp/tree_merger-tmp_dest_dir-K4flMPFy.tmp/app/styles/app.[scss|sass] does not exist
```
And *that* I'm not sure how to fix.
```sh
$ ember --version
version: 0.2.0-beta.1
node: 0.12.0
npm: 2.1.8
```

**Comment by miguelcobain** [comment]
Please create a file in app/styles/app.scss, even if empty.
You can use css in that file as well.

I know it isn't the best approach possible, but it was a good step forward in including sass in addons. It's temporary.

@stefanpenner, can you help me here? It looks like I can't use broccoli-sass/broccoli-autoprefixer without the consuming app installing it as well?

**Comment by hhff** [comment]
@miguelcobain you can in the the 0.2.0 beta

related:
https://github.com/ember-cli/ember-cli/releases/tag/v0.2.0-beta.1
https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#setuppreprocessorregistry

**Comment by miguelcobain** [comment]
Exactly what we need! Made some progress.
Currently the styles don't show up in the consuming app. Maybe I need to sass import the styles?

**Comment by miguelcobain** [comment]
@kazimuth can you try with version 0.0.16 and follow the new installation instructions: https://github.com/miguelcobain/ember-paper#installation ?

I think I nailed it.

**Comment by kazimuth** [comment]
Still failing with `Cannot find module 'broccoli-autoprefixer'` :/

**Comment by kazimuth** [comment]
Also, when I've installed things, I'm now getting:
```sh
$ ember build
Build failed.
File: bower_components/qunit/src/intro
Unexpected token (13:0)
SyntaxError: Unexpected token (13:0)
    at raise (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at parseExprAtom (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2153:7)
    at parseExprSubscripts (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
    at parseMaybeUnary (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
    at parseExprOps (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
    at parseMaybeConditional (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
    at parseMaybeAssign (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
    at parseExpression (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
    at parseStatement (test/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
```
I have no idea if this is related - it's an acorn problem, which seems out of left field.

**Comment by miguelcobain** [comment]
Just ran:

```bash
$ ember new paper-test
$ cd papert-test
$ npm install --save-dev broccoli-autoprefixer
$ npm install --save-dev broccoli-sass
$ mv app/styles/app.css app/styles/app.scss
```

then created added the line `@import 'ember-paper';`.

Then `ember server` ran fine.

**Comment by kazimuth** [comment]
Cleaned caches, everything works now. Thanks!

**Comment by miguelcobain** [comment]
Any particular reason for reopening?

**Comment by kazimuth** [comment]
...Not intentional.

**Comment by SirZach** [comment]
what if you don't have an app.css file, but an app.less file instead? and what if you're doing everything in less and not sass in general?

**Comment by miguelcobain** [comment]
Yes, good point, but:

If you need to override sass variables, you'll need to use sass.
The way other libraries offer support for less and sass is to have both less and sass stylesheets available. Then users just include what they need.
Seems fine to me, but a bit overkill at the moment (there are definitely other priorities).

Additionally, if we're going to choose between sass and less, I'd rather use sass because it lets us use css syntax if desired (scss files).

**Comment by SirZach** [comment]
@miguelcobain I was unable to get the app to compile having both less and sass pre-compilers. It seemed that having both an <code>app.less</code> and an <code>app.scss</code> was troublesome. Luckily, I'm not too invested into either of the technologies so switching my app over to sass fixed the issue but I can't imagine that's a good solution for everyone.

BTW - I didn't even want access to ember-paper's variables but I was still forced to create an <code>app.scss</code> :(

**Comment by miguelcobain** [comment]
Supporting both less and sass pre-compilers in your app isn't an ember-paper concern, I think.

However, since this PR https://github.com/ember-cli/ember-cli/pull/1918 I think it should be possible.

> BTW - I didn't even want access to ember-paper's variables but I was still forced to create an app.scss :(

AFAIK, there isn't any way to add sass to an app, from an addon, without importing its stylesheets.
Example: [ember-cli-bootstrap-sass](https://github.com/unionups/ember-cli-bootstrap-sass) requires you to import its sass styles.

Let's keep an eye for other addons and check if they do this in a better way.

**Comment by SirZach** [comment]
I guess what I was trying to say was that I couldn't build my app with ember-paper unless I had an <code>app.scss</code> file and I couldn't have that file because I already had an <code>app.less</code>. I had to convert my app to use sass instead of less which was not ideal.

**Comment by miguelcobain** [comment]
Right now, you **need** an `app.scss` to import ember-paper sass styles, and I don't think there is any other way.

However, this shouldn't stop you from using less simultaneously in your app! You should able to have a `app.scss` and an `app.less` simultaneously. There is a PR in ember-cli that aims to address just that: https://github.com/ember-cli/ember-cli/pull/1918
There may be some problem somewhere, though...

**Comment by SirZach** [comment]
Ok, tonight I'll try a brand new ember-cli app using less and ember-paper and see if I get the same problems.

**Comment by miguelcobain** [comment]
:+1:

**Comment by ivanoats** [comment]
I'm getting this issue on a brand new ember 0.2.3 CLI app.  

```
ember install ember-paper                                                                                                                                  
version: 0.2.3
Installed packages for tooling via npm.
Cannot find module 'broccoli-autoprefixer'
Error: Cannot find module 'broccoli-autoprefixer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ivan/dev/blah/node_modules/ember-paper/index.js:4:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by jaichandra** [comment]
@SirZach - Im trying to integrate ember-paper into a project that already uses less and ran into this same issue. Were you able to get ember-paper working with less? I am seeing below error on build

---
File not found: /app/styles/app.scss
in any of the following include paths:
  /Users/.../tmp/sass_compiler-input_base_path-50K8SQUz.tmp/0
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /Users/.../tmp/sass_compiler-input_base_path-50K8SQUz.tmp/0
    at Object.findFileSync (/Users/.../node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/Users/.../node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:62:31)
    at /Users/.../node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/.../node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/.../node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/.../node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/.../node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
---
I have both app.scss and app.less files under styles folder.

package.json (in the same sequence):
"ember-cli-less": "1.3.3",
"ember-cli-sass": "5.2.1",

**Comment by SirZach** [comment]
@jaichandra #248 was where I tracked not having that `app.scss` file and the resolution was to remove `broccoli-sass` from the project. `broccoli-sass` was originally used by ember-paper and they migrated away from it so that's the first thing I would check for.

**Comment by Syzygy24** [comment]
@jaichandra did you ever resolve this? I'm seeing the same thing.
