### ISSUE TITLE
Getting a file to import not found or unreadable when importing

### ISSUE THREAD

**Issue by Jordan4jc** [miguelcobain/ember-paper#71]
When I try to import the sass file in the app.scss file I am getting this error in the terminal that is running the ember server

```
FSEventStreamStart failed
Error: FSEventStreamStart failed
    at null.<anonymous> (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
unable to resolve root /Users/jordanriser/workspace/blog/client/bower_components/hammerjs: directory /Users/jordanriser/workspace/blog/client/bower_components/hammerjs is not watched
Error: unable to resolve root /Users/jordanriser/workspace/blog/client/bower_components/hammerjs: directory /Users/jordanriser/workspace/blog/client/bower_components/hammerjs is not watched
    at null.<anonymous> (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
unable to resolve root /Users/jordanriser/workspace/blog/client/bower_components/ember-cli-moment-shim: directory /Users/jordanriser/workspace/blog/client/bower_components/ember-cli-moment-shim is not watched
Error: unable to resolve root /Users/jordanriser/workspace/blog/client/bower_components/ember-cli-moment-shim: directory /Users/jordanriser/workspace/blog/client/bower_components/ember-cli-moment-shim is not watched
    at null.<anonymous> (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/jordanriser/workspace/blog/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

I am only getting this when trying to import ember paper, I made sure to install broccoli sass first and then ember paper but when I get to the import step I get this error.

**Comment by miguelcobain** [comment]
Which ember-cli and node version are you running?

**Comment by Jordan4jc** [comment]
`ember -v` returns 
version: 0.2.0
node: 0.12.0
npm: 2.7.0

**Comment by miguelcobain** [comment]
Please try:

```bash
rm -rf node_modules bower_components dist tmp
npm cache clean
bower cache clean
npm install
bower install
```

I've solved so many problems like this that I always try it first.

**Comment by Jordan4jc** [comment]
This worked, thank you
