### ISSUE TITLE
Cannot find module 'angular-material-source/package.json' 

### ISSUE THREAD

**Issue by avdept** [miguelcobain/ember-paper#972]
Hello. Getting this error while trying to run tests on circleCI. Have latest version - `^1.0.0-beta.8`. Locally works perfectly, on CI it runs with very basic config - `npm install` && `npm run test` 
Any ideas what am I doing wrong?

**Comment by sir-dunxalot** [comment]
I am experiencing this error message when running `ember try:each` locally with Ember CLI `~3.3.0`.

Reinstalling dependencies did not solve the issue.

Here is the stack trace from one of the ember-try scenarios:

```sh
  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'angular-material-source/package.json' from '/Users/me/Codebases/ember-google-charts/node_modules/ember-paper'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'angular-material-source/package.json' from '/Users/me/Codebases/ember-google-charts/node_modules/ember-paper'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'angular-material-source/package.json' from '/Users/me/Codebases/ember-google-charts/node_modules/ember-paper'
    at Function.module.exports [as sync] (/Users/me/Codebases/ember-google-charts/node_modules/resolve/lib/sync.js:43:15)
    at Class.pathBase (/Users/me/Codebases/ember-google-charts/node_modules/ember-paper/index.js:231:33)
    at Class.treeForStyles (/Users/me/Codebases/ember-google-charts/node_modules/ember-paper/index.js:205:44)
    at Class.superWrapper [as treeForStyles] (/Users/me/Codebases/ember-google-charts/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/Users/me/Codebases/ember-google-charts/node_modules/ember-cli/lib/models/addon.js:583:33)
    at Class.treeFor (/Users/me/Codebases/ember-google-charts/node_modules/ember-cli/lib/models/addon.js:543:21)
    at project.addons.reduce (/Users/me/Codebases/ember-google-charts/node_modules/ember-cli/lib/broccoli/ember-app.js:660:26)
    at Array.reduce (<anonymous>)
    at EmberAddon._addonTreesFor (/Users/me/Codebases/ember-google-charts/node_modules/ember-cli/lib/broccoli/ember-app.js:658:32)
    at EmberAddon.addonTreesFor (/Users/me/Codebases/ember-google-charts/node_modules/ember-cli/lib/broccoli/ember-app.js:682:17)
```

**Comment by sir-dunxalot** [comment]
No, unfortunately I wasn't able to get any further towards the root cause of the issue so I removed `ember-paper` from the app and the issue went away. Since it's a small and basic app, that seems like a good enough solution for me especially if this issue isn't widespread.

**Comment by avdept** [comment]
@miguelcobain Any update on this? Getting circleCI crashing while using ember-paper

**Comment by dan-tailormed** [comment]
also crashing on bitbucket pipeline, any updates?

**Comment by dan-tailormed** [comment]
adding "angular-material-source": "^1.0.10", to package.json seem to solve the issue

**Comment by abobwhite** [comment]
I am getting something very similar and I've done this all from a fresh install of `ember-paper` with `ember install ember-paper`, deleted `tmp`, `node_modules`, `package-lock.json`, and `dist` and completely did a fresh install. My error is slightly different on `npm start`.

```
Build Error (Funnel)

ENOENT: no such file or directory, lstat '/Users/ARW0214/Git/my-app/node_modules/angular-material-source/src/core/services/layout/layout.scss
```

ember-cli 3.6.0
ember-paper 1.0.0-beta.22

**Comment by abobwhite** [comment]
Update: This is the issue I'm having and it just started happening with no other changes to map app setup: https://github.com/miguelcobain/ember-paper/issues/1069
